mlboard:
  Image:
    Name: kuberlab/mlboard
    Tag: v3
  persistence:
    fromProvider: true
    storageClass: anything
    accessMode: ReadWriteOnce
    size: 10Gi
    volume:
      hostPath:
        path: /var/lib/mlboard-postgresql/data
  nodeSelector:
    enabled: false
    labels:
      mlboard: mlboard

global:
  useRBAC: true