mlboard:
  Image:
    Name: kuberlab/mlboard
    Tag: v3
  cron:
    enabled: false
  fetching:
    pattern: '0 * * * *'
    prometheusInterval: '60m'
  persistence:
    fromProvider: true
    accessMode: ReadWriteOnce
    #storageClass: anything
    size: 10Gi
    volume:
      hostPath:
        path: /var/lib/mlboard-postgresql/data
  nodeSelector:
    enabled: false
    labels:
      mlboard: mlboard

global:
  useRBAC: true
