mlboard:
  Image:
    Name: kuberlab/mlboard
    Tag: v3
  cron:
    enabled: false
  fetching:
    pattern: '0 * * * *'
    prometheusInterval: '60m'
  postgres:
    persistence:
      fromProvider: true
      accessMode: ReadWriteOnce
      #storageClass: anything
      size: 10Gi
      volume:
        hostPath:
          path: /var/lib/mlboard-postgresql/data
  git:
    persistence:
      fromProvider: true
      accessMode: ReadWriteOnce
      #storageClass: anything
      size: 10Gi
      volume:
        hostPath:
          path: /var/lib/mlboard-git/data
  nodeSelector:
    enabled: false
    labels:
      mlboard: mlboard

  dealer_limits: true
  pvcCreation:
    className: ""
    #persistentVolumeSource:
    #  nfs:
    #    server: 127.0.0.1
    #    path: /

global:
  useRBAC: true