apiVersion: v1
kind: PersistentVolume
metadata:
  name: "data-{{.Values.workspace}}"
  annotations:
    {{- if .Values.volumes.data.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.volumes.data.storageClass | quote }}
    {{- end }}
  labels:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: data
spec:
  {{- if .Values.volumes.data.storageClass }}
  storageClassName: {{ .Values.volumes.data.storageClass | quote }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.volumes.data.size | quote }}
  nfs:
    path: "{{ printf "%s/%s" .Values.volumes.data.nfs.path .Values.workspace }}"
    server: {{ .Values.volumes.data.nfs.server }}