apiVersion: v1
kind: Service
metadata:
  name: "jupyter-{{.Values.workspace}}"
  labels:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: jupyter
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  type: {{ .Values.jupyter.serviceType }}
  ports:
    - port: 8888
      name: jupyter
      targetPort: 8888
  selector:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: jupyter