apiVersion: v1
kind: ConfigMap
metadata:
  name: mlboard-config
data:
  mlboard.yaml: |
    dealer_limits: {{ .Values.mlboard.dealerLimits }}
    storage:
{{ toYaml .Values.mlboard.pvcCreation | indent 6 }}
