{{- if .Values.global.useRBAC }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-bind-mlboard
  labels:
    app: mlboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-mlboard
subjects:
- kind: ServiceAccount
  name: mlboard
  namespace: {{ .Release.Namespace }}
{{- end }}
