{{- if .Values.global.useRBAC }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-mlboard
rules:
- apiGroups: ["", "autoscaling", "extensions", "apps", "rbac.authorization.k8s.io"] # "" indicates the core API group
  resources:
    - secrets
    - events
    - roles
    - rolebindings
    - serviceaccounts
    - namespaces
    - pods
    - pods/log
    - pods/exec
    - deployments
    - replicasets
    - statefulsets
    - services
    - configmaps
    - nodes
    - pods/status
    - role-mlboard
    - persistentvolumeclaims
    - persistentvolumes
    - horizontalpodautoscalers
  verbs:
    - bind
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
{{- end }}
