apiVersion: v1
kind: Secret
metadata:
  name: mlboard-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: kuberlab
    component: postgresql
type: Opaque
data:
  postgres-password:  "amRqY25ETiEzaW5Oa1otIzg="