apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlboard-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlboard
    component: postgresql
spec:
  template:
    metadata:
      labels:
        app: mlboard
        component: postgresql
    spec:
      {{- if .Values.mlboard.nodeSelector.enabled }}
      nodeSelector:
      {{- range $key, $value := .Values.mlboard.nodeSelector.labels }}
        {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- end }}
      containers:
      - name: postgresql
        image: "postgres:9.5.4"
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: PGUSER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlboard-postgresql
              key: postgres-password
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data/pgdata
            subPath: dealer-db
      volumes:
      - name: data
        {{- if .Values.mlboard.persistence.fromProvider }}
        persistentVolumeClaim:
          claimName: mlboard-postgresql
        {{- else }}
{{ toYaml .Values.mlboard.persistence.volume | indent 8 }}
        {{- end }}
