apiVersion: v1
kind: Service
metadata:
  name: "tensorbord-{{.Values.workspace}}"
  labels:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: tensorbord
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  type: {{ .Values.tensorbord.serviceType }}
  ports:
    - port: 6006
      name: tensorbord
      targetPort: 6006
  selector:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: tensorbord