apiVersion: v1
kind: Service
metadata:
  name: "tensorboard-{{.Values.workspace}}"
  labels:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: tensorboard
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  type: {{ .Values.tensorboard.serviceType }}
  ports:
    - port: 6006
      name: tensorboard
      targetPort: 6006
  selector:
    app: mlboard
    heritage: "{{ .Release.Service }}"
    workspace: {{.Values.workspace}}
    component: tensorboard